---
# tasks file for ansible-role-haproxy

- name: Update apt cache on Debian Family os
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_os_family == "Debian"

- name: Update emerge cache on Gentoo
  shell: emerge-webrsync
  changed_when: false
  when: ansible_os_family == "Gentoo"

- name: Install haproxy
  package:
    name: "{{ haproxy_package }}"
    state: present

- name: Manage haproxy service
  service:
    name: "{{ haproxy_service }}"
    enabled: yes
    state: started
